- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Making Sprites w/ p5.game.js"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Adding asteroids to the game"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Collision detection"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Adding sprite animations"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Shooting lasers"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Fixing some bugs"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Adding a background image and a score board"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Adding sound effects"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Game Over screen"]
  paths: ["./game.js", "./index.html", "./assets/**"]
- assignment: 5886420c9d778aa8a103bf25ca5f63c1
  section: ["Extra features"]
  paths: ["./game.js", "./index.html", "./assets/**"]